/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "jvmti.h"
/* Header for class com_skyinu_jvmti_libwrapper_NativeBridge */

#ifndef _Included_com_skyinu_jvmti_libwrapper_NativeBridge
#define _Included_com_skyinu_jvmti_libwrapper_NativeBridge
#endif

/*
 * Class:     com_skyinu_jvmti_libwrapper_NativeBridge
 * Method:    getObjSize
 * Signature: (Ljava/lang/Object;)J
 */
JNIEXPORT jlong JNICALL Java_com_skyinu_jvmti_libwrapper_NativeBridge_getObjSize
  (JNIEnv *, jclass, jobject);

